### ISSUE TITLE
Impossibilité de créer une tâche sous Google Chrome

### ISSUE THREAD

**Issue by KBPGD** [wilsto/BoardOS#146]
Sous Chrome (Version 54.0.2840.87), il n'est pas possible de créer une nouvelle tâche. Le formulaire de saisie ne s'affiche pas.

![image](https://cloud.githubusercontent.com/assets/23334257/20095068/37d71554-a5a4-11e6-9fce-9e13847304c6.png)

Edit : même problème sous IE 11. Problème de profil utilisateur ?

**Comment by wilsto** [comment]
Le profil a été changé en 'manager', la création de tache est possible désormais
