### ISSUE TITLE
Tâche non prise en compte dans le dashboard

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#186]
Bonjour Willy, 

Je viens de créer un tâche (BOSS - Pilotage - implementation REX Q1)  avec pour activité : DCLIC.CBI.BICS.CM.pilotage.REX. 

Cette nouvelle tâche n’apparaît alors pas dans le dashboard CM dans lequel toutes les activités commençant par DCLIC.CBI.BICS.CM devraient apparaître. 

Merci pour ta réponse,

William

**Comment by wilsto** [comment]
Je vais ajouter un bouton pour rafraichir le dashboard de facon manuel si de manière auto, il y a eu un raté
