### ISSUE TITLE
Problème (mineur) affichage page de connexion

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#274]
Bonjour, 
Il y a un problème dans l'affichage de la page de connexion à BOSS (cf photo) malgré rafraîchissement de la page. 
Bonne journée
![capture](https://user-images.githubusercontent.com/10065368/27275016-e9320670-54d5-11e7-9291-ac9b23f3e49b.PNG)

**Comment by wilsto** [comment]
Corrigé
![image](https://user-images.githubusercontent.com/4889715/27308666-23531dce-5550-11e7-9db1-138c8cc16364.png)
