### ISSUE TITLE
[BOSS REC] - Action plan

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#311]
Willy, 

Je viens de tester l'action plan sur BOSS en REC.
En passant par le dashboard, si je clique sur "create an action plan" il ne se passe rien
En passant par la tâche ça fonctionne bien, je peux créer mon plan d'action. Cependant, une fois créé le PA n'est pas rattaché à la tâche ou au dashboard. 
En PJ sur Slack la vidéo.

**Comment by wilsto** [comment]
Corrigé
