### ISSUE TITLE
BOSS REC - Rattacher anomalie à une tâche corrective

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#365]
Willy, 
Une fois l'ano déclarée, si je clique sur CA pour ajouter une action corrective, le système n'associe pas la tâche créée à l'ano. D'ailleurs la tâche n'est créée n'est pas visible sur le dashboard (cf vidéo slack)

**Comment by wilsto** [comment]
je ferme l'ano et note une évolution, pour l'instant faut que je vois comment que je vois comment passer les informations depuis le dashboard que je crée une tache pour une ano et que les deux sont reliés
