### ISSUE TITLE
BOSS Rec - création dashboard 

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#367]
Bonjour Willy, 
Quand je cherche à créer un nouveau dashboard, par défaut il m'affiche dans le bandeau permettant de voir l'aborescence (Home > dashboard) le nom du dashboard multi change. 
De plus, est-ce normal, une fois qu'on a cliqué sur create dashboard d'arriver sur une page blanche? il faut donc cliquer sur menu puis sur show and or modify dashboard... 
Cf vidéo sur slack

**Comment by wilsto** [comment]
le nom de l'ancien dashboard supprimé

**Comment by wilsto** [comment]
la configuration est maintenant activé par défaut pour une création de dashbaord
