### ISSUE TITLE
Calcul de la confiance 

### ISSUE THREAD

**Issue by CedDev** [wilsto/BoardOS#392]
Ce calcul prend en compte pour l'instant les taches not started est ce normal ?

**Comment by wilsto** [comment]
![image](https://user-images.githubusercontent.com/4889715/32978350-c9eb42ee-cc40-11e7-8e7a-a170c8ac8050.png)

**Comment by wilsto** [comment]
Prise en compte que le calcul de la KPI s'effectue uniquement si tache terminée
