### ISSUE TITLE
Incohérence date d'engagement tâche vs calendrier

### ISSUE THREAD

**Issue by wbri17** [wilsto/BoardOS#422]
Bonjour Willy, 

Je viens de créer une tâche (DECID P1 - Mise à jour e-learning) avec un engagement du 05/01 au 12/01. 
Cependant sur le calendrier de la homepage cette tâche s'affiche du 01/01 au 03/01. 

La vidéo sur slack sera plus explicite.

**Comment by wilsto** [comment]
![image](https://user-images.githubusercontent.com/4889715/34637652-10391366-f2bb-11e7-8925-4fc6b53d43e1.png)

Peux tu me confirmer que tu as toujours le problème ? je n'arrive pas à le reproduire

**Comment by wbri17** [comment]
Willy, 
Je viens de vérifier, sur le calendrier en vue mensuelle tout est ok c’est sur la vue hebdo que le problème est toujours présent cf captures d’ecrzns sur slack
